# Generated by Django 4.2.2 on 2023-09-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='sid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
